### ISSUE TITLE
Error with dot net 07 

### ISSUE THREAD

**Issue by deepakn1079** [CamiloTerevinto/TerevintoSoftware.StaticSiteGenerator#7]
when i try to use the tool for asp.net core project that targets dotnet 07 , it gives error 

Unhandled exception: System.Exception: Error while configuring services
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.AspNetCore.Mvc.RazorPages, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.AspNetCore.Mvc.RazorPages, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at TerevintoSoftware.StaticSiteGenerator.Startup.ConfigureServices() in /home/runner/work/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/Utilities/Startup.cs:line 34
   --- End of inner exception stack trace ---
   at TerevintoSoftware.StaticSiteGenerator.Startup.ConfigureServices() in /home/runner/work/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/Utilities/Startup.cs:line 64
   at TerevintoSoftware.StaticSiteGenerator.StaticSiteBuilder.GenerateStaticSite(StaticSiteGenerationOptions staticSiteOptions, Boolean writeOutputLogs) in /home/runner/work/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/TerevintoSoftware.StaticSiteGenerator/StaticSiteBuilder.cs:line 23

**Comment by CamiloTerevinto** [comment]
Hey @deepakn1079, any updates on this?
